name: Publish snapshot build

on:
  push:
    branches: [master]
    paths: ['**/*.kt', '**/*.kts', '**/*.properties', '**/*.toml']

env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PORTAL_TOKEN }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'pinterest/ktlint'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: ./.github/actions/setup-gradle-build

      - name: Publish snapshot to Maven
        run: ./gradlew clean publishMavenPublicationToMavenCentralRepository

      - name: Publish Kotlin-dev snapshot to Maven
        run: ./gradlew -PkotlinDev clean publishMavenPublicationToMavenCentralRepository
