# name must be identical to name of 'pull-request-with-code'
name: Pull request

on:
  push:
    branches: ['master']
    paths:
      - '**/*'
      - '!**/*.kt'
      - '!**/*.kts'
      - '!**/*.properties'
      - '!**/*.toml'
  pull_request:
    paths:
      - '**/*'
      - '!**/*.kt'
      - '!**/*.kts'
      - '!**/*.properties'
      - '!**/*.toml'

# Add a dummy job that return true so that a PR not containing any code can be merged to master
# Note that "jobs.build.strategy" and "jobs.build.runs-on" should be kept in sync with "pull-request-wth-code"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: 'echo "No build required"'
